### ISSUE TITLE
Support other Archlinux-based distro

### ISSUE THREAD

**Issue by marty-macfly** [lectrode/xs-update-manjaro#38]
Hello,

Most of what you've done is working properly also on Archlinux, would be an issue for you to make it compatible for both OS ?

Only things which are not working to make it compatible with Arch are:
* `manjaro-keyring manjaro-system` which are not required on Arch L#714
* `pacman-mirrors` update which doesn't exist on Arch, workaround is just to disable that feature on Arch.

Are you open to PR to improve that ?

**Comment by marty-macfly** [comment]
Also adding a licence would be nice.

**Comment by lectrode** [comment]
Hi Marty,

Funny, I was just thinking about what it would take to make it more distro-agnostic a few days ago.

PR is welcome, although I'll probably want to implement slightly more than just basic checks for this.

NOTE: The following code snippets have not been tested and may need some refinement

Excluding `pacman-mirrors` is easy enough:
```
if ! type pacman-mirrors >/dev/null 2>&1; then trouble "pacman-mirrors not found - skipping"
elif perst_isneeded "${conf_a[update_mirrors_freq]}" "${perst_a[last_mirrors_update]}"; then
    trouble "Updating Mirrors... [branch: $(pacman-mirrors -G 2>/dev/null)]"
    (pacman-mirrors $pacmirArgs || pacman-mirrors -g) 2>&1 |sed 's/\x1B\[[0-9;]\+[A-Za-z]//g' |tr -cd '\11\12\15\40-\176' |tee -a $log_f
    err_mirrors=${PIPESTATUS[0]}; if [[ $err_mirrors -eq 0 ]]; then
        perst_update "last_mirrors_update"; else trouble "ERR: pacman-mirrors exited with code $err_mirrors"; fi
fi
```

Skipping `manjaro-keyring` and `manjaro-system` are also fairly straight-forward:
```
trouble "Updating system packages..."
$pcmbin -S --needed --noconfirm $(chk_pkgisinst archlinux-keyring && echo archlinux-keyring) $(chk_pkgisinst manjaro-keyring && echo manjaro-keyring) $(chk_pkgisinst manjaro-system && echo manjaro-system) 2>&1 |tee -a $log_f
err_sys=${PIPESTATUS[0]}; if [[ $err_sys -ne 0 ]]; then trouble "ERR: pacman exited with code $err_sys"; fi
```

However, if other Arch-based distros (or Arch itself) have other system packages that should be updated before anything else, that should probably be supported in some way as well. For example, if there is a `arch-system` package added at some point, it'd be nice for my script to support that.

There are 2 options for addressing that:

1. hardcode checks for packages for varying distros
  * con: lack of end-user control
  * con: would require keeping tabs on relevant packages for Arch and Arch-based distros (or relying on users to report them)
  * pro: has the potential to be automatic without requiring additional config


2. Introduce a new config setting (probably `main_syspkgs_str`) that the end-user could manually configure for their distro (manjaro pkgs would still have hard-coded checks)
  * con: manual config on other distros
  * pro: more end-user control
  * pro: more potential arch-based distro support without having to hardcode package checks
 
Of those 2 options, I'm definitely leaning toward the 2nd. It should still be relatively easy to implement.

**Comment by lectrode** [comment]
a license is something i've definitely been putting off...i'll try to look into that when i have time.
for now, this project can be copied, modified, and used freely however you want

**Comment by lectrode** [comment]
@marty-macfly 
Noticed you had attempted to add this script to the AUR. While I don't have a problem with you doing that, there were a couple things I noticed about the way you packaged it:

### xs-autoupdate.service
* You added `KillMode=process` (👍)
  * Didn't realize KillMode was an option - I'm now including that. Thanks

* You disabled the background fork (👎)
  * if someone enables that process to run on startup (which this script is designed for), without the fork it will block the system from starting until it completes
  * The reason it forks is so that the system is usable even while it is updating. Otherwise, people (especially on slower connections) will be stuck sitting there waiting for packages to download and install. I've seen updates take 2-3 hours in rural areas - people should be able to use their computers during this time.
  * Not only that, but if the person doesn't have time to sit there waiting for the updates, they should not be prevented from putting the system in suspend mode (or hibernate). If it's stuck starting up, they can't do that (think especially of laptops)

* You disabled the "RemainAfterExit" (🤔)
  *  I believe this was set to 'yes' in order to allow the final notification to remain on the screen after the script finished. I'll have to look into whether or not that is still needed.


### xs-autoupdate.timer
* Interesting use of the update script
* Only problem I see with this is that if the computer is indeed idle for 60 minutes before it starts, the user probably won't be there to manually reboot the computer if critical packages were updated (like systemd or the kernel or crypto services). This can lead to a scenario where the user comes back to their computer only to find that they are no longer authenticated with the session, and cannot reauthenticate. This also prevents them from gracefully restarting their computer, as their unauthenticated session will not have permission to reboot.
* If you have `reboot_1enable_num=0` in the config file, that will restart the computer specifically in this scenario only (https://github.com/lectrode/xs-update-manjaro/commit/72c08035ee18afbf94c4235cf71149b3387ab8e8 fixed that setting - before it was treating 0 like 1)

**Comment by lectrode** [comment]
Closed this issue, as the requested features were implemented and are now in the latest stable release.
(you can still reply here to discuss despite the issue being closed)
